config: !!python/object:types.Config
  auto_trigger_cooldown: false
  batch_size: 128
  clip_norm: 0.0
  data_dir: ~/.code/latent-space/datasets/cifar
  debug_mode: false
  decay_type: cosine
  epochs: 10
  experiment_name: default
  frac_warmup: 0.0
  img_size: 32
  losses: !!python/tuple
  - !!python/object:argparse.Namespace
    circle_gamma: 256.0
    circle_m: 0.25
    name: cross_entropy
    start_epoch: 0
    warmup_epochs: 0
    weight: 1.0
  lr: 0.001
  lr_min_factor: 0.0
  model_name: vit-tiny
  num_batches: 391
  num_classes: 10
  num_workers: 4
  output_dir: ./runs
  overfit_batches: 0.0
  patch_size: 4
  pin_memory: false
  save_embeddings: false
  scale: 0.08
  scheduler_name: cosine
  seed: -1
  start_cooldown_immediately: false
  umap_min_dist: 0.1
  umap_n_neighbors: !!python/tuple
  - 15
  use_bfloat16: false
  use_cifar100: false
  use_mhc: false
  weight_decay: 0.0
