name: CML-Slurm-Train
on: [push]

jobs:
  launch-runner:
    runs-on: [self-hosted, slurm]
    steps:
      - name: Launch Runner on Slurm
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # We call the globally installed cml binary directly
          cml runner launch \
            --labels=cml-gpu \
            --cloud=slurm \
            --idle-timeout=300 \
            --single \
            --slurm-args="--partition=all"
            
  train:
    needs: launch-runner
    runs-on: [self-hosted, cml-gpu]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Training
        run: |
          python train.py
          
          echo "## Training Results" > report.md
          echo "Run on node: $(hostname)" >> report.md
          
          # If you can't use cml-send-comment action, use the cli:
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}