name: cifar-10-lightning
on: workflow_dispatch

jobs:
    run:
        runs-on: [self-hosted, cml, gpu]
        permissions:
            contents: write
            pull-requests: write
            issues: write
        defaults:
            run:
                shell: bash -exo pipefail {0}
        steps:
            - uses: actions/checkout@v3
            - name: Setup
              run: |
                  git submodule update --init --recursive
                  echo "Current working directory: $(pwd)"
                  chmod -R 777 ~/.cache/uv
                  uv venv --python 3.10
                  fish -c "source .venv/bin/activate.fish; fish setup.fish --dino"
                  dvc remote add -d --local wpeb-print /home/richw/.code/latent-space/.dvc/cache
                  dvc pull /root/.code/latent-space/datasets/cifar.dvc

            - name: Train model
              env:
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  nvidia-smi
                  fish -c "source .venv/bin/activate.fish; fish src/cifar_lightning/run.fish --debug-mode"
            - name: Create PR
              if: success()
              env:
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo "## Metrics" >> report.md
                  git fetch --prune --no-recurse-submodules
                  cat out/metrics.txt >> report.md
                  # dvc metrics diff main --md >> report.md || echo "_no baseline to diff against_" >> report.md

                  echo "## Plots" >> report.md
                  [ -f out/pacmap_emb.png ] && echo "![](./out/pacmap_emb.png)" >> report.md
                  [ -f out/umap_nn15_emb.png ] && echo "![](./out/umap_nn15_emb.png)" >> report.md

                  dvc add out
                  git add out.dvc report.md .gitignore
                  dvc push -r wpeb-print

                  cml pr create --branch="experiment/run-$GITHUB_RUN_ID" --target-branch main

# cml pr create
# Global Options:
#   --log                    Logging verbosity
#           [string] [choices: "error", "warn", "info", "debug"] [default: "info"]
#   --driver                 Git provider where the repository is hosted
#     [string] [choices: "github", "gitlab", "bitbucket"] [default: infer from the
#                                                                     environment]
#   --repo                   Repository URL or slug
#                                   [string] [default: infer from the environment]
#   --driver-token, --token  CI driver personal/project access token (PAT)
#                                   [string] [default: infer from the environment]
#   --help                   Show help                                   [boolean]

# Options:
#   --md                   Output in markdown format [](url)             [boolean]
#   --skip-ci              Force skip CI for the created commit (if any) [boolean]
#   --merge, --auto-merge  Try to merge the pull request upon creation   [boolean]
#   --rebase               Try to rebase-merge the pull request upon creation
#                                                                        [boolean]
#   --squash               Try to squash-merge the pull request upon creation
#                                                                        [boolean]
#   --branch               Pull request branch name                       [string]
#   --target-branch        Pull request target branch name                [string]
#   --title                Pull request title                             [string]
#   --body                 Pull request description                       [string]
#   --message              Commit message                                 [string]
#   --remote               Git remote                 [string] [default: "origin"]
#   --user-email           Git user email[string] [default: "olivaw@iterative.ai"]
#   --user-name            Git user name         [string] [default: "Olivaw[bot]"]