name: cifar-10-lightning
on: workflow_dispatch

jobs:
  run:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - name: Cleanup
        run: rm -rf $GITHUB_WORKSPACE && mkdir -p $GITHUB_WORKSPACE

      - name: Checkout
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/white-richard/latent-space.git $HOME/latent-space
      - name: Setup
        run: |
          cd $HOME/latent-space
          uv venv .venv
          source .venv/bin/activate
          fish setup.fish

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $HOME/latent-space
          source .venv/bin/activate
          fish src/cifar_lightning/run.fish --debug-mode
          cat out/metrics.txt >> report.md